export const KnustHostels = [
  {
    id: '1',
    title: 'CANAM HALL',
    location: 'AYEDUASE',
    price:"2000",
    image: require('../assets/aprt.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '2',
    title: 'CEPOS HOSTEL',
    price:"3000",
    location: 'AYEDUASE',
    image: require('../assets/franco.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '3',
    title: 'DAKENS INT. HOSTEL',
    location: 'AYEDUASE',
    price:"4000",
    image: require('../assets/frontline.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '4',
    price:"5000",
    title: 'MASS HOSTEL',
    location: 'AYEDUASE NEW SITE',
    image: require('../assets/mass.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '5',
    price:"6000",
    title: 'ABUNDANCE GRACE HOSTEL',
    location: 'Kentenkrono',
    image: require('../assets/aprt.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '7',
    price:"2000",
    title: 'DE-LISA HOSTEL MAIN',
    location: 'Kotei Road',
    image: require('../assets/frontlineapt.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '8',
    price:"5000",
    title: 'FRANCO HOSTEL',
    location: 'Kotei Extension',
    image: require('../assets/franco.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '9',
    price:"5000",
    title: 'FRANCO HOSTEL ANNEX',
    location: 'Kotei Extension',
    image: require('../assets/mireku.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '10',
    price:"5000",
    title: 'FRONTLINE INN',
    location: 'Ayeduase',
    image: require('../assets/morning.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '11',
    price:"5000",
    title: 'GHANA HOSTELS',
    location: 'GAZA',
    image: require('../assets/nyame.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '12',
    price:"5000",
    title: 'HONESTY STUDENTS HOSTEL',
    location: 'Ahinsan Estate',
    image: require('../assets/happy.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '13',
    price:"5000",
    title: 'AJECADO HOSTEL',
    location: 'Kentenkrono',
    image: require('../assets/whitehouse.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
];
export const UGHostels = [
  {
    id: '1',
    title: 'Aseda Hostel',
    location: 'Main campus',
    price:"2000",
    image: require('../assets/aseda.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '2',
    title: 'Akuafo Hall',
    price:"3000",
    location: 'Main Campus',
    image: require('../assets/bani-hostel.png'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '3',
    title: 'TF Hostel',
    location: 'Main Campus',
    price:"4000",
    image: require('../assets/TF-Hostel.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '4',
    price:"5000",
    title: 'Heavens Gate Hostel',
    location: 'Kentenkrono',
    image: require('../assets/heavens-gate-hostel.png'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '5',
    price:"6000",
    title: 'Evandy HOSTEL',
    location: 'Legon',
    image: require('../assets/evandy.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '7',
    price:"2000",
    title: 'Benzee-Residency',
    location: 'Legon',
    image: require('../assets/Benzee-Residency.png'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '8',
    price:"5000",
    title: 'Pentagon HOSTEL',
    location: 'Legon',
    image: require('../assets/house4.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '9',
    price:"5000",
    title: 'Sand City Hostel',
    location: 'Legon',
    image: require('../assets/sandcity-hostel.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '10',
    price:"5000",
    title: 'West End Hostel',
    location: 'Legon',
    image: require('../assets/Westend-hostel.jpeg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '11',
    price:"5000",
    title: 'ABUNDANCE GRACE HOSTEL',
    location: 'Kentenkrono',
    image: require('../assets/house4.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '12',
    price:"5000",
    title: 'ABUNDANCE GRACE HOSTEL',
    location: 'Kentenkrono',
    image: require('../assets/house4.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '13',
    price:"5000",
    title: 'ABUNDANCE GRACE HOSTEL',
    location: 'Kentenkrono',
    image: require('../assets/house4.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
];
export const UPSAHostels = [
  {
    id: '1',
    title: 'Unity hall',
    location: 'Main campus',
    image: require('../assets/house1.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '2',
    title: 'Katanga Hall',
    location: 'Main Campus',
    image: require('../assets/house2.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '3',
    title: 'African Hall',
    location: 'Main Campus',
    image: require('../assets/house3.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '4',
    title: 'Private Hostel',
    location: 'Kentenkrono',
    image: require('../assets/house4.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
];

export const UCCHostels = [
  {
    id: '1',
    title: 'Unity hall',
    location: 'Main campus',
    image: require('../assets/house1.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '2',
    title: 'Katanga Hall',
    location: 'Main Campus',
    image: require('../assets/house2.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '3',
    title: 'African Hall',
    location: 'Main Campus',
    image: require('../assets/house3.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
  {
    id: '4',
    title: 'Private Hostel',
    location: 'Kentenkrono',
    image: require('../assets/house4.jpg'),
    details: `This building is located in the commercial area, withing walking distance of shops...`,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
  },
];